//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.RoomBookeds = new HashSet<RoomBooked>();
        }
    
        public int BookingID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string DurationStay { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public string BookingPaymentType { get; set; }
        public Nullable<int> TotalRoomsBooked { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> GuestID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomBooked> RoomBookeds { get; set; }
    }
}
