//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public string EmployeeDesignation { get; set; }
        public Nullable<int> EmployeeAddressID { get; set; }
        public string EmployeeContactNumber { get; set; }
        public string EmployeeEmail { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Department Department { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
