//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotels()
        {
            this.Bookings = new HashSet<Bookings>();
            this.Employees = new HashSet<Employees>();
            this.HotelChainHasHotel = new HashSet<HotelChainHasHotel>();
            this.Rooms = new HashSet<Rooms>();
        }
    
        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public string HotelContactNumber { get; set; }
        public string HotelEmailAddress { get; set; }
        public string HotelWebsite { get; set; }
        public string HotelDescription { get; set; }
        public Nullable<int> HotelFloorCount { get; set; }
        public Nullable<int> HotelRoomCapacity { get; set; }
        public Nullable<int> HotelChainID { get; set; }
        public int AddressID { get; set; }
        public Nullable<int> StarRatingID { get; set; }
        public Nullable<System.TimeSpan> CheckInTime { get; set; }
        public Nullable<System.TimeSpan> CheckOutTime { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelChainHasHotel> HotelChainHasHotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rooms> Rooms { get; set; }
    }
}
