//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelChainHasHotel
    {
        public int HotelChainID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        public virtual HotelChain HotelChain { get; set; }
        public virtual Hotels Hotels { get; set; }
    }
}
