//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBooked
    {
        public int RoomBookedID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
